language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
addons:
  postgresql: "9.4"
before_script:
  - npm install -g grunt-cli
  - psql -c 'create database pg_restify;' -U postgres
script:
  - npm test
  - grunt coveralls
